language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "zhudk"
  - git config user.email "1126572821@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://5P2ropJqjBGIAIRJrc5_AQ@lumiazdk/lumiazdk.github.io.git" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: git@github.com:lumiazdk/lumiazdk.github.io.git